development:
  adapter: postgresql
  encoding: utf8
  database: autentificacion_development
  pool: 5
  username: postgres
  password: STYLESHIT
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: autentificacion_test
  pool: 5
  username: postgres
  password: STYLESHIT
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: autentificacion_production
  username: postgres
  password: STYLESHIT
  host: localhost
  port: 5432
